from pathlib import Path
p=Path('app/infrastructure/challenges/application_fixtures.py');s=p.read_text(encoding='utf-8').replace('system_wrapper="You are a careful React/TypeScript coding agent. Follow the player\'s instructions. Return only structured replacements for the provided editable files.",','system_wrapper=("You are a careful React/TypeScript coding agent. "\n                    "Follow the player\'s instructions. Return only structured replacements "\n                    "for the provided editable files."),').replace('including a dotted domain. Plus-addresses are valid.', 'including "\n        "a dotted domain. Plus-addresses are valid.').replace('footer working. Edit only the declared source files.', 'footer working. "\n        "Edit only the declared source files.');p.write_text(s,encoding='utf-8')
p=Path('app/infrastructure/application/starter_projects.py');s=p.read_text(encoding='utf-8');s=s.replace('if lock.get("lockfileVersion") != 3:', 'dependencies = json.loads((source / "package.json").read_text(encoding="utf-8-sig"))\n                expected = {"react":"19.2.0", "react-dom":"19.2.0"}\n                development = {"typescript":"5.9.3", "esbuild":"0.25.12", "@types/react":"19.2.0", "@types/react-dom":"19.2.0"}\n                if dependencies.get("dependencies") != expected or dependencies.get("devDependencies") != development or dependencies.get("scripts"):\n                    raise ValueError("Unapproved dependency policy")\n                root_lock = lock.get("packages", {}).get("", {})\n                if root_lock.get("dependencies") != expected or root_lock.get("devDependencies") != development:\n                    raise ValueError("Dependency lock does not match package")\n                if lock.get("lockfileVersion") != 3:');p.write_text(s,encoding='utf-8')
p=Path('app/infrastructure/application/sandbox.py');s=p.read_text(encoding='utf-8').replace('from dataclasses import asdict','from dataclasses import asdict, replace');s=s.replace('self._invoke({"health": True}, SandboxPolicy())','self._invoke({"health": True}, replace(SandboxPolicy(), timeout_seconds=15))');s=s.replace('            screenshots = []','            for stage in ("typecheck", "build", "browser"):\n                duration = result.get("metrics", {}).get(stage)\n                if isinstance(duration, (int, float)) and 0 <= duration <= 120:\n                    logging.getLogger(__name__).info("sandbox_stage", extra={"stage":stage,"duration_seconds":duration})\n            screenshots = []');p.write_text(s,encoding='utf-8')
p=Path('app/domains/execution/application.py');s=p.read_text(encoding='utf-8').replace('            try:\n                agent_result', '            agent_started = time.monotonic()\n            try:\n                agent_result');s=s.replace('            try:\n                edits = parse_agent_edits', '            logging.getLogger(__name__).info("application_agent", extra={"duration_seconds": time.monotonic() - agent_started})\n            try:\n                edits = parse_agent_edits');p.write_text(s,encoding='utf-8')
p=Path('../frontend/src/features/admin/application-editor.tsx');s=p.read_text(encoding='utf-8');s=s.replace('import type { ApplicationDefinition', 'import { useState } from "react";\nimport { checkPackageHealth } from "./api";\nimport type { ApplicationDefinition');s=s.replace('  const pkg =', '  const [health, setHealth] = useState<{id:string;message:string;busy:boolean} | null>(null);\n  async function healthCheck(id: string) {\n    setHealth({id,message:"Checking package…",busy:true});\n    try { const result = await checkPackageHealth(id); setHealth({id,busy:false,message:!result.available ? "Executable challenges aren’t available on this server right now." : result.build_succeeded && result.checks_initialized ? "Starter builds and browser checks initialize. Intentional challenge defects may still fail checks." : "Starter health check failed. Check the configured runtime."}); }\n    catch { setHealth({id,busy:false,message:"Package health could not be verified."}); }\n  }\n  const pkg =');s=s.replace('<small>Runtime policy is maintained in the repository.</small>','<small>Runtime policy is maintained in the repository.</small><p><button className="admin-secondary" type="button" disabled={health?.busy} onClick={() => void healthCheck(pkg.id)}>Check package health</button></p>{health?.id === pkg.id ? <p role="status">{health.message}</p> : null}');p.write_text(s,encoding='utf-8')
p=Path('../frontend/src/features/admin/api.ts');s=p.read_text(encoding='utf-8');s+='''
export async function checkPackageHealth(id: string): Promise<{available: boolean; build_succeeded: boolean | null; checks_initialized: boolean}> {
  const response = await fetch(`/api/admin/application-packages/${encodeURIComponent(id)}/health`, {method:"POST"});
  if (!response.ok) throw new Error("Package health could not be verified.");
  return response.json();
}
''';p.write_text(s,encoding='utf-8')
