/* eslint-disable @next/next/no-img-element -- authenticated package previews are backend PNGs. */
import { useState } from "react";
import { checkPackageHealth } from "./api";
import type { ApplicationDefinition, ApplicationLimits, ApplicationPackage, PackageCheck } from "./application-types";
import { copyPackageDefaults, toggleSelection } from "./application-types";

export function ApplicationEditor({ value, packages, onChange }: { value: ApplicationDefinition | null; packages: ApplicationPackage[]; onChange: (value: ApplicationDefinition) => void }) {
  const [health, setHealth] = useState<{id:string;message:string;busy:boolean} | null>(null);
  async function healthCheck(id: string) {
    setHealth({id,message:"Checking package…",busy:true});
    try { const result = await checkPackageHealth(id); setHealth({id,busy:false,message:!result.available ? "Executable challenges aren’t available on this server right now." : result.build_succeeded && result.checks_initialized ? "Starter builds and browser checks initialize. Intentional challenge defects may still fail checks." : "Starter health check failed. Check the configured runtime."}); }
    catch { setHealth({id,busy:false,message:"Package health could not be verified."}); }
  }
  const pkg = packages.find((item) => item.id === value?.package_id);
  const limitLabels: Record<keyof ApplicationLimits, string> = { agent_timeout_seconds: "Agent timeout (seconds)", build_timeout_seconds: "Build timeout (seconds)", browser_timeout_seconds: "Browser timeout (seconds)", max_file_bytes: "Maximum bytes per file", max_files: "Maximum changed files", max_log_chars: "Build log character limit" };
  function checks(title: string, field: "visible_checks" | "hidden_checks", choices: PackageCheck[]) {
    if (!value) return null;
    return <section className={`admin-panel${field === "hidden_checks" ? " application-private" : ""}`} id={field === "hidden_checks" ? "hidden-checks" : "visible-checks"}>
      <div className="admin-section-heading"><div><p className="section-kicker">{field === "hidden_checks" ? "PRIVATE · ADMIN ONLY" : "PLAYER FEEDBACK"}</p><h2>{title}</h2></div><span className="admin-index">{value[field].length} selected</span></div>
      <p className="admin-help">{field === "hidden_checks" ? "Submit returns aggregate results only. These check details stay private." : "Run shows these checks with clear pass and fail feedback."}</p>
      <div className="application-check-options">{choices.map((check) => <label className="application-check-option" key={check.id}><input type="checkbox" checked={value[field].includes(check.id)} onChange={() => onChange({ ...value, [field]: toggleSelection(value[field], check.id) })} /><span><strong>{check.label}</strong><small>{check.viewports.length ? check.viewports.map((id) => pkg?.defaults.viewports.find((v) => v.id === id)?.label ?? id).join(" · ") : "Source / build check"}{check.count > 1 ? ` · ${check.count} elements` : ""}{check.min_width_ratio ? ` · minimum width ${check.min_width_ratio * 100}%` : ""}</small></span></label>)}</div>
    </section>;
  }
  return <>
    <section className="admin-panel" id="application"><div className="admin-section-heading"><div><p className="section-kicker">STATIC HTML / CSS</p><h2>Application package</h2></div></div>
      <label className="admin-field"><span>Package</span><select value={value?.package_id ?? ""} onChange={(event) => { const selected = packages.find((item) => item.id === event.target.value); if (selected) onChange(copyPackageDefaults(selected)); }}><option value="" disabled>Select a package</option>{packages.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label>
      {!packages.length ? <p className="admin-alert danger">The package catalog could not be loaded. Reload this page to try again.</p> : null}
      {pkg && value ? <><p className="admin-help"><strong>{pkg.execution_mode === "sandboxed_executable" ? "Sandboxed Executable" : "Static HTML / CSS"}</strong></p>{pkg.runtime_metadata ? <div className="runtime-policy"><h3>Trusted runtime policy</h3><p>{pkg.runtime_metadata.runtime} · Network disabled</p><p>{pkg.runtime_metadata.cpus} CPU · {pkg.runtime_metadata.memory_mb} MB memory · {pkg.runtime_metadata.pids} processes · {pkg.runtime_metadata.timeout_seconds}s maximum</p><p>Commands: {pkg.runtime_metadata.commands.join(" → ")}</p><small>Runtime policy is maintained in the repository.</small><p><button className="admin-secondary" type="button" disabled={health?.busy} onClick={() => void healthCheck(pkg.id)}>Check package health</button></p>{health?.id === pkg.id ? <p role="status">{health.message}</p> : null}</div> : null}<p className="admin-help">{pkg.description}</p><div className="application-package-preview">{pkg.defaults.viewports.filter((v) => v.screenshot).slice(0, 1).map((v) => <figure className="starter-preview" key={v.id}>{pkg.execution_mode === "sandboxed_executable" ? <div className="shot-empty">Interactive React / TypeScript app. Use package health to verify the runtime before testing.</div> : <img src={`/api/admin/application-packages/${pkg.id}/preview/${v.id}.png`} alt={`${pkg.display_name} starter at ${v.width}px`} />}<figcaption>Starter · {v.label} · {v.width}px</figcaption></figure>)}<div><h3>Editable files</h3><p className="admin-help">Choose the files this version lets the coding agent change.</p>{pkg.defaults.editable_files.map((file) => <label className="application-check-option" key={file}><input type="checkbox" checked={value.editable_files.includes(file)} onChange={() => onChange({ ...value, editable_files: toggleSelection(value.editable_files, file) })} /><code>{file}</code></label>)}<p className="admin-help">Starter, build, measurement sizes, and check parameters are maintained with this repository package.</p></div></div></> : null}
    </section>
    {pkg && value ? <>{checks("Visible checks", "visible_checks", pkg.visible_checks)}{checks("Hidden checks", "hidden_checks", pkg.hidden_checks)}
      <section className="admin-panel" id="screenshots"><div className="admin-section-heading"><div><p className="section-kicker">RESULT VIEWS</p><h2>Screenshots</h2></div></div><p className="admin-help">Select result views and name their artifact labels. Private measurement views remain private.</p><div className="admin-grid two">{value.viewports.filter((view) => pkg.defaults.viewports.find((v) => v.id === view.id)?.screenshot).map((view) => <div className="authoring-item" key={view.id}><label className="application-check-option"><input type="checkbox" checked={view.screenshot} onChange={() => onChange({ ...value, viewports: value.viewports.map((v) => v.id === view.id ? { ...v, screenshot: !v.screenshot } : v) })} /><strong>{view.width} × {view.height}</strong></label><label className="admin-field"><span>Artifact label · {view.id}</span><input maxLength={60} value={view.label} onChange={(event) => onChange({ ...value, viewports: value.viewports.map((v) => v.id === view.id ? { ...v, label: event.target.value } : v) })} /></label></div>)}</div></section>
      <section className="admin-panel" id="execution-limits"><div className="admin-section-heading"><div><p className="section-kicker">EXECUTION BUDGET</p><h2>Execution limits</h2></div></div><p className="admin-help">Limits may be reduced from the package maximum.</p><div className="admin-grid three">{(Object.keys(limitLabels) as (keyof ApplicationLimits)[]).map((key) => <label className="admin-field" key={key}><span>{limitLabels[key]}</span><input type="number" min={1} max={pkg.defaults.limits[key]} value={value.limits[key]} onChange={(event) => onChange({ ...value, limits: { ...value.limits, [key]: Number(event.target.value) } })} /><small>Maximum {pkg.defaults.limits[key]}</small></label>)}</div></section>
    </> : null}
  </>;
}
