from typing import Protocol

from app.application.admin.models import AdminChallengeRecord, AdminChallengeSummary


class AdminChallengeRepository(Protocol):
    async def list_all(self) -> tuple[AdminChallengeSummary, ...]: ...

    async def get_by_slug(self, slug: str) -> AdminChallengeRecord | None: ...

    async def create(self, record: AdminChallengeRecord) -> None: ...

    async def update_draft(self, record: AdminChallengeRecord) -> None: ...

    async def create_version(self, record: AdminChallengeRecord) -> None: ...

    async def publish(self, slug: str, version: str) -> AdminChallengeRecord: ...

    async def unpublish(self, slug: str) -> AdminChallengeRecord: ...
